name: Build Bat to Exe and Create Release

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: windows-latest  # This action needs to run on a Windows runner

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Bat To Exe Converter
      run: |
        choco install bat-to-exe -y
      shell: powershell

    - name: Build .bat to .exe
      run: |
        # Replace 'your_script.bat' with the actual name of your .bat file
        battoexeconverter -bat "checks.bat" -save "checks.exe"
      shell: cmd

    - name: Upload .exe artifact
      uses: actions/upload-artifact@v2
      with:
        name: Exe build 
        path: checks.exe
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: ./checks.exe  # Path to the .exe file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Release URL
      id: release_url
      run: echo "Release URL: ${{ steps.create_release.outputs.upload_url }}"
